package com.us.model;

import com.us.model.Person;


        function void printName(String name,String desc) {
            System.out.println("name:"+name+" desc:"+ desc);
        }


        rule "boy"
            salience 1
            when
                $p : Person(age > 0);
            then
                $p.setDesc("少年");
                retract($p);
                printName($p.getName(),$p.getDesc());
        end

        rule "youth"
            salience 2
            when
                $p : Person(age > 12);
            then
                $p.setDesc("青年");
                retract($p);
                printName($p.getName(),$p.getDesc());
        end

        rule "midlife"
            salience 3
            when
                $p : Person(age > 24);
            then
                $p.setDesc("中年");
                retract($p);
                printName($p.getName(),$p.getDesc());
        end

        rule "old"
        lock-on-active true

          salience 5
            when
                $p : Person(age > 60 && age <80)

            then
                $p.setDesc("老年");
                update($p);
                printName($p.getName(),$p.getDesc());
        end