server:
  port: 8881
spring:
  application:
    name: aliconsumer-user
  boot:
    admin:
      client:
        url: http://localhost:8000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8999

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  sentinel:
    enabled: true

info:
  app:
    name: ${spring.application.name}
    description: UserCURD功能的调用者
  build:
    artifactId: @project.artifactId@
    version: @project.version@