server:
  port: 8000

spring:
  profiles:
    active: local
  application:
    name: admin-server
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

info:
  app:
    name: ${spring.application.name}
    description: SpringBootAdmin 服务器

---
spring:
  profiles: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: cluster

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka,http://eureka3:8763/eureka